
class ohmicity_shared:

    venue_array = [
        '210', 
        "blue rooster", 
        'burger-ish', 
        "river roo", 
        "cage brewing", 
        "cask & ale", 
        "cask and ale", 
        "coconut", 
        "cottonmouth", 
        "daiquiri deck raw bar siesta key", 
        "darwin", 
        "del frisco", 
        "dockside", 
        "drunken clam",
        "dearborn", 
        "floridian social club", 
        "flute", 
        "gator club",
        "gilligan", 
        "green iguana", 
        "hideaway", 
        "hula bay", 
        "independent bar st petersburg", 
        "independent bar and cafe tampa", 
        "island time",
        "joyland", 
        "hatters", 
        "marina jack", 
        "mattison's city grille", 
        "mattison's riverwalk grille", 
        "motorworks", 
        "new world brewery", 
        "o'brien", 
        "pete's place north", 
        "ringside cafe", 
        "ruby's elixir",
        "sandBar", 
        "hard rock", 
        "sharky", 
        "siesta key oyster bar", 
        "skipper", 
        "st pete side lot", 
        "stottlemyer", 
        "straggler", 
        "tj carney", 
        "tamiami tap", 
        "the castle", 
        "the pub tampa bay", 
        "the tavern at bayboro",
        "whiskey barrel", 
        "whiskey wings - st peterburg", 
        "toasted monkey", 
        "white elephant pub", 
        "wild rover brewery"
    ]

    band_data_path = '/Volumes/Work/Face2Face/Xity/streetTeam/Scrappers/Show Data/Band Data'
    venue_data_path = '/Volumes/Work/Face2Face/Xity/streetTeam/Scrappers/Show Data/Venue Data'
    
    
